services:
  db:
    image: timescale/timescaledb:latest-pg15
    environment:
      POSTGRES_USER: cylvy
      POSTGRES_PASSWORD: cylvy_secure_password
      POSTGRES_DB: cylvy_analyzer
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/migrations:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U cylvy"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: postgresql://cylvy:cylvy_secure_password@db:5432/cylvy_analyzer
      REDIS_URL: redis://redis:6379
      SECRET_KEY: ${SECRET_KEY:-development-secret-key-change-in-production-min-32-chars}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY:-dev-jwt-secret-change-in-production}
      ENVIRONMENT: development
      STORAGE_PATH: /app/storage
      
      # API Keys (set via environment or configure in admin portal)
      OPENAI_API_KEY: ${OPENAI_API_KEY:-}
      SCALE_SERP_API_KEY: ${SCALE_SERP_API_KEY:-}
      SCRAPINGBEE_API_KEY: ${SCRAPINGBEE_API_KEY:-}
      COGNISM_API_KEY: ${COGNISM_API_KEY:-}
      YOUTUBE_API_KEY: ${YOUTUBE_API_KEY:-}
      
      # Generic Dimensions Feature Configuration
      GENERIC_DIMENSIONS_ENABLED: true
      OPENAI_MODEL_GENERIC_ANALYSIS: gpt-4-1106-preview
      EVIDENCE_ANALYSIS_TIMEOUT: 45
      MAX_DIMENSIONS_PER_ANALYSIS: 20
      DYNAMIC_PROMPT_MAX_LENGTH: 16000
    ports:
      - "8001:8000"
    volumes:
      - ./backend:/app
      - ./backend/storage:/app/storage
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    command: >
      sh -c "
        echo 'Initializing database...' &&
        python -m app.db.migrate init &&
        echo 'Database ready. Starting application...' &&
        uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
      "
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: development
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:8001/api/v1
      NEXT_PUBLIC_WS_URL: ws://localhost:8001/ws
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      - backend
    command: npm run dev

volumes:
  postgres_data:
  redis_data:

